version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html/src
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
